// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raqgoebefpsstxbkuajp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcWdvZWJlZnBzc3R4Ymt1YWpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTQ0NzgsImV4cCI6MjA1OTc5MDQ3OH0.SeY14i-RV_uDHCKl98OQXrrDIt64OiTC-yrrGaCd6EA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);